title: "Базы данных"
url: https://das-dasein.github.io
baseurl: /db-lovefield
logo: database.svg
search_enabled: false

# Enable or disable heading anchors
heading_anchors: true

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

theme: jekyll-theme-cayman
